
# Do not check this file in to github or other public repositories

development:
  url_base: 'http://localhost:4567'
  mavenn: 'http://mavenn.com'
  apid: "your-apid"
  token: "your-token"

production:
  url_base: 'http://nyx.memamsa.com'
  mavenn: 'http://mavenn.com'
  apid: "your-apid"
  token: "your-token"

